/*
 * Year: 2017
 */
package userInterface;

import applicationLogic.DatabaseActivity;
import applicationLogic.JWebProfileActivity;
import applicationLogic.SearchResult;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.eclipse.egit.github.core.client.GitHubClient;

/**
 *
 * @author nandan
 */
public class GithubSetupChooser extends javax.swing.JFrame {

    /**
     * Creates new form GithubSetupChooser
     */
    Connection con;
    org.eclipse.egit.github.core.User user;
    GitHubClient github;
    JWebProfileActivity profileActivity;
    javax.swing.JButton resultButton;

    public GithubSetupChooser(Connection con, org.eclipse.egit.github.core.User user, GitHubClient github) {
        this.con = con;
        this.user = user;
        this.github = github;
        initComponents();
        jLabel1.setText("You are about to add " + user.getName() + " to jWebProfile");
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("You are about to add Nandan Desai to jWebProfile");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add a new jWebProfile with Github a/c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Connect with an existing Twitter a/c");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 3, 3));
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Task1(null).execute();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String name;
            jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            profileActivity = new JWebProfileActivity(con);
            ArrayList<SearchResult> results;
            results = profileActivity.getAllTWITTERScreenNamesWithNoGithub();
            for (SearchResult result : results) {
                name = profileActivity.getTWITTERname(result.username);
                System.out.println("twitter user name with no twitter :" + name);
                Image image = result.photo.getImage();
                Image newimg = image.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
                result.photo = new ImageIcon(newimg);
                resultButton = new javax.swing.JButton(name);
                resultButton.setBackground(Color.white);
                resultButton.setIcon(result.photo);
                resultButton.setActionCommand(result.username);
                resultButton.addActionListener(resultButtonListener1);
                jPanel2.add(resultButton);
                resultButton.updateUI();
                jPanel2.updateUI();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Could not retrieve data from database. Data may not be found. Check for errors");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    ActionListener resultButtonListener1 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent eve) {
            new Task1(eve.getActionCommand()).execute();
        }
    };

    class Task1 extends SwingWorker<Void, Void> {

        /*
         * Main task. Executed in background thread.
         */
        String twitterScreenName;

        Task1(String twitterScreenName) {
            this.twitterScreenName = twitterScreenName;
        }

        @Override
        public Void doInBackground() {
            jProgressBar1.setVisible(true);
            jProgressBar1.setIndeterminate(true);
            Boolean added = DatabaseActivity.githubNewProfileInsert(con, user, github, twitterScreenName);
            if (added) {
                JOptionPane.showMessageDialog(null, user.getName() + "'s Github a/c is successfully added to jWebProfile");
            } else {
                JOptionPane.showMessageDialog(null, "The user was not added to the jWebProfile.\nThe user might already be present in the database or there might be some error.");
            }
            //DatabaseActivity.deleteTwitterUser(con, user);

            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            jProgressBar1.setVisible(false);
            dispose();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
