/*
 * Year: 2017
 */
package userInterface;

import applicationLogic.DatabaseActivity;
import applicationLogic.JWebProfileActivity;
import applicationLogic.SearchResult;
import com.jcabi.github.Github;
import com.jcabi.github.Search;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import twitter4j.Twitter;
import twitter4j.User;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.SwingWorker;
import org.eclipse.egit.github.core.client.GitHubClient;
import org.eclipse.egit.github.core.service.UserService;
import org.jachievement.Achievement;
import org.jachievement.AchievementConfig;
import org.jachievement.AchievementPosition;
import org.jachievement.AchievementQueue;

/**
 *
 * @author nandan
 */
public class HomePageUI extends javax.swing.JFrame {

    Connection con;
    Twitter twitter;
    String myScreenName;
    GitHubClient github;
    Github githubSearch;
    String myLoginName;
    /**
     * Creates new form HomePageUI
     */

    //Local utility variables
    javax.swing.JButton resultButton;
    JWebProfileActivity profileActivity;

    public HomePageUI(Connection con, Twitter twitter, String myScreenName, GitHubClient github, Github githubSearch, String myLoginName) {
        this.con = con;
        this.twitter = twitter;
        this.myScreenName = myScreenName;
        this.github = github;
        this.githubSearch = githubSearch;
        this.myLoginName = myLoginName;
        initComponents();
        jProgressBar1.setVisible(false);
        jProgressBar2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel18.setVisible(false);
        jLabel5.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jLabel19.setVisible(false);
        String twitterGuide = "<html><p>This is Twitter search section. You can search for any Twitter user by entering their name in the above search box.</p>"
                + "<p>Go ahead! Search for a friend, a celebrity, a politician or anyone you are interested in!</p>"
                + "<html>";
        String githubGuide = "<html><p>This is Github search section. You can search for any Github user by entering their name in the above search box.</p>"
                + "<p>Go ahead! Search for a developer! For example, try searching for Linus Torvalds, the creator of Linux!</p>"
                + "<html>";
        jLabel23.setText(twitterGuide);
        jLabel25.setText(githubGuide);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jWebProfile");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setToolTipText("You need to enter the full name of the person you want to search");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 390, 30));

        jLabel1.setFont(new java.awt.Font("Lato Thin", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jWebProfile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, 30));

        jLabel24.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 185, 166));
        jLabel24.setText("jWebProfile is ready to use!");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(0, 2, 3, 3));
        jScrollPane1.setViewportView(jPanel7);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 950, 410));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 950, 10));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("View all existing profiles/Refresh");
        jButton3.setToolTipText("You need to press this button to refresh the panel after you add a new jWebProfile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/logo60.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/whiteHomepageHoodie.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 1600, 580));

        jTabbedPane1.addTab("          View an existing jWebProfile       ", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/twitter logo final.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 320, 520));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jLabel2.setText("Enter the name of the user");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lato Thin", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 255));
        jLabel23.setText("jLabel23");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 780, 410));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(0, 2, 3, 3));
        jScrollPane2.setViewportView(jPanel6);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 840, 390));

        jLabel5.setText("Select a user from the results below...");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel5.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 170, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Working on it... Please wait!");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/logo60.png"))); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 890, 540));

        jTabbedPane1.addTab("              Add a new Twitter a/c to jWebProfile               ", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/github social.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Enter the name of the user");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel9.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jLabel25.setFont(new java.awt.Font("Lato Thin", 1, 24)); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 820, 390));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(0, 2, 3, 3));
        jScrollPane3.setViewportView(jPanel11);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 840, 390));
        jPanel9.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 170, 20));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setText("Working on it... Please wait!");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel19.setText("Select a user from the results below...");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/logo60.png"))); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 890, 540));

        jTabbedPane1.addTab("Add a new Github a/c to jWebProfile", jPanel3);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("More profiles will be added in future!");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/twitter icon.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/github icon.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/google-plus.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/linkedin.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/youtube.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("and more...");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel15.setText("jWebProfile © 2017");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel16.setText("Want to donate? Bitcoin address: ");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 255));
        jLabel26.setText("15qfjqXsveLzhrRQLPifkCZaMaev4D8Gry");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel7))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))))
                .addContainerGap(424, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(jLabel15))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel16)))
                .addGap(0, 615, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(jLabel15))
        );

        jTabbedPane1.addTab("+", jPanel10);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 570));

        jMenu4.setText("Misc.");

        jMenuItem5.setText("Clean up the Database");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Factory reset");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Report a bug");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Help");

        jMenuItem1.setText("Need help with usage of this software");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Contact the creators");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("About");

        jMenuItem3.setText("About jWebProfile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Making of jWebProfile");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class Task1 extends SwingWorker<Void, Void> {

        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground() {
            jLabel23.setVisible(false);
            jLabel5.setVisible(true);
            jScrollPane2.setVisible(true);
            jProgressBar1.setVisible(true);
            jProgressBar1.setIndeterminate(true);
            jLabel6.setVisible(true);

            try {
                jPanel6.removeAll();
                jPanel6.repaint();
                jPanel6.revalidate();
                List<User> users = twitter.searchUsers(jTextField2.getText(), 0);
                if (!users.iterator().hasNext()) {
                    JOptionPane.showMessageDialog(null, "No results found for your query.");
                }
                for (User user : users) {
                    System.out.println("Seeing the ImageIcon");
                    URL url = new URL(user.getBiggerProfileImageURLHttps());
                    BufferedImage img = ImageIO.read(url);
                    ImageIcon icon = new ImageIcon(img);
                    //System.out.println(user.getMiniProfileImageURL());
                    resultButton = new javax.swing.JButton(user.getName());
                    resultButton.setIcon(icon);
                    resultButton.setBackground(Color.white);
                    resultButton.setActionCommand(user.getScreenName());
                    resultButton.addActionListener(resultButtonListener1);
                    jPanel6.add(resultButton);
                    resultButton.updateUI();
                    jPanel6.updateUI();
                }
            } catch (NullPointerException ne) {
                JOptionPane.showMessageDialog(null, "No results can be shown. There might be an error.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No results.\n This might be due to some network error.\nPlease try again.");
                System.out.println(e);
            }

            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            jProgressBar1.setVisible(false);
            jLabel6.setVisible(false);
        }
    }

    class Task2 extends SwingWorker<Void, Void> {

        /*
         * Main task. Executed in background thread.
         */
        ActionEvent eve;

        void setEvent(ActionEvent e) {
            this.eve = e;
        }

        @Override
        public Void doInBackground() {
            jProgressBar1.setVisible(true);
            jProgressBar1.setIndeterminate(true);
            jLabel6.setVisible(true);

            try {
                User user = twitter.showUser(eve.getActionCommand());
                System.out.println(user.getDescription());

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        javax.swing.JFrame twitterSearchResultui = new TwitterSearchResultOverview(con, twitter, user);
                        URL iconURL = getClass().getResource("/userInterface/Resources/logo512.png");
                        ImageIcon icon = new ImageIcon(iconURL);
                        twitterSearchResultui.setIconImage(icon.getImage());
                        twitterSearchResultui.setLocationRelativeTo(null);
                        twitterSearchResultui.setVisible(true);
                    }
                });

            } catch (Exception e) {
                System.out.println(e);
            }

            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            jProgressBar1.setVisible(false);
            jLabel6.setVisible(false);
        }
    }

    class Task3 extends SwingWorker<Void, Void> {

        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground() {
            jLabel25.setVisible(false);
            jScrollPane3.setVisible(true);
            jLabel19.setVisible(true);
            jProgressBar2.setVisible(true);
            jProgressBar2.setIndeterminate(true);
            jLabel18.setVisible(true);
            try {
                int count = 0;
                jPanel11.removeAll();
                jPanel11.repaint();
                jPanel11.revalidate();
                String queryName = jTextField3.getText();
                org.eclipse.egit.github.core.User user;
                UserService userService = new UserService(github);
                Search search = githubSearch.search();
                Iterable<com.jcabi.github.User> resultUsers = search.users(queryName, "followers", Search.Order.DESC);
                if (!resultUsers.iterator().hasNext()) {
                    JOptionPane.showMessageDialog(null, "No results found for your query.");
                }
                for (com.jcabi.github.User resultUser : resultUsers) {

                    user = userService.getUser(resultUser.login());
                    System.out.println("Getting the user with login " + user.getLogin());
                    URL url = new URL(user.getAvatarUrl());
                    System.out.println("Image url for github is " + user.getAvatarUrl());
                    BufferedImage img = ImageIO.read(url);
                    ImageIcon icon = new ImageIcon(img);
                    Image image = icon.getImage();
                    Image newimg = image.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
                    icon = new ImageIcon(newimg);
                    resultButton = new javax.swing.JButton(user.getName());
                    resultButton.setIcon(icon);
                    resultButton.setBackground(Color.white);
                    resultButton.setActionCommand(user.getLogin());
                    resultButton.addActionListener(resultButtonListener3);
                    jPanel11.add(resultButton);
                    System.out.println("added the resultButton to jPanel11");
                    resultButton.updateUI();
                    jPanel11.updateUI();
                    count++;
                    if (count >= 20) {
                        break;
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            jProgressBar2.setVisible(false);
            jLabel18.setVisible(false);
        }
    }

    class Task4 extends SwingWorker<Void, Void> {

        /*
         * Main task. Executed in background thread.
         */
        ActionEvent eve;

        void setEvent(ActionEvent e) {
            this.eve = e;
        }

        @Override
        public Void doInBackground() {
            jProgressBar2.setVisible(true);
            jProgressBar2.setIndeterminate(true);
            jLabel18.setVisible(true);

            try {
                UserService userService = new UserService(github);
                org.eclipse.egit.github.core.User user = userService.getUser(eve.getActionCommand());

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        javax.swing.JFrame githubSearchResultui = new GithubSearchResultOverview(con, user, github);
                        githubSearchResultui.setLocationRelativeTo(null);
                        URL iconURL = getClass().getResource("/userInterface/Resources/logo512.png");
                        ImageIcon icon = new ImageIcon(iconURL);
                        githubSearchResultui.setIconImage(icon.getImage());
                        githubSearchResultui.setVisible(true);
                    }
                });

            } catch (Exception e) {
                System.out.println(e);
            }

            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            jProgressBar2.setVisible(false);
            jLabel18.setVisible(false);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Task1().execute();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel24.setVisible(false);
        jScrollPane1.setVisible(true);

        try {
            //this is for searching the jWebProfile from search bar
            //this is not has been updated to new methods
            System.out.println("Hearing your click");
            String queryName = jTextField1.getText();
            String name;
            profileActivity = new JWebProfileActivity(con);
            if (profileActivity.checkIfUserExists(queryName)) {
                System.out.println("The queryName exists");
                jPanel7.removeAll();
                jPanel7.repaint();
                jPanel7.revalidate();
                ArrayList<SearchResult> resultsUsernames;
                resultsUsernames = profileActivity.getjWebProfileUsernamesForGivenQuery(queryName);
                for (SearchResult username : resultsUsernames) {
                    ///System.out.println("Getting the username: "+username);
                    name = profileActivity.getNameOfThejWebProfile(username.twitterScreenName, username.githubLoginName);
                    resultButton = new javax.swing.JButton(name);
                    resultButton.setBackground(Color.white);
                    resultButton.setActionCommand(profileActivity.getValidUsernameFromjWebProfile(username));
                    resultButton.addActionListener(resultButtonListener2);
                    jPanel7.add(resultButton);
                    resultButton.updateUI();
                    jPanel7.updateUI();

                }
                System.out.println("Finished hearing your click");
            } else {
                JOptionPane.showMessageDialog(null, "No jWebProfile found for this query. You may want to set it up.");
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "No jWebProfile found for this query :( Do you want to set it up?");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {

            new Task1().execute();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel24.setVisible(false);
        jScrollPane1.setVisible(true);
        dbSearch();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void dbSearch() {
        try {
            //this is when you click search all existing profiles
            String name;

            jPanel7.removeAll();
            jPanel7.repaint();
            jPanel7.revalidate();
            profileActivity = new JWebProfileActivity(con);
            ArrayList<SearchResult> results;
            results = profileActivity.getAlljWebProfileUsernames();
            for (SearchResult searchResultObj : results) {
                //System.out.println("Getting the username: "+username);
                System.out.println(searchResultObj.twitterScreenName + ":" + searchResultObj.githubLoginName);
                name = profileActivity.getNameOfThejWebProfile(searchResultObj.twitterScreenName, searchResultObj.githubLoginName);
                System.out.println("Name of the jWebProfile: " + name);
                resultButton = new javax.swing.JButton(name);
                resultButton.setBackground(Color.white);
                resultButton.setActionCommand(profileActivity.getValidUsernameFromjWebProfile(searchResultObj));
                System.out.println("Valid username :" + profileActivity.getValidUsernameFromjWebProfile(searchResultObj));
                resultButton.addActionListener(resultButtonListener2);
                jPanel7.add(resultButton);
                resultButton.updateUI();
                jPanel7.updateUI();

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            //write a method for this.
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new Task3().execute();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            new Task3().execute();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        int opinion = JOptionPane.showConfirmDialog(null, "Note that all the saved jWebProfiles will be permanently lost. \nBut, your login session will still be retained.\n Are you sure you want to do this?");
        if (opinion == JOptionPane.YES_OPTION) {
            DatabaseActivity.TESTcleanAllTables(con);
            JOptionPane.showMessageDialog(null, "The database is clean. Now you can start fresh!");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        int opinion = JOptionPane.showConfirmDialog(null, "Warning! The whole database will be wiped. Your login sessions, and saved jWebProfiles will be lost.\nYou will again have to login in the next restart of this software.\n Are you sure you want to continue?");
        if (opinion == JOptionPane.YES_OPTION) {
            DatabaseActivity.deleteAllTables(con);
            JOptionPane.showMessageDialog(null, "The database has been completely wiped out. You can restart jWebProfile manually");
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Visit https://jwebprofile.blogspot.com");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Mail me at: nkdesai409@gmail.com");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame about = new AboutJWebProfile();
                about.setLocationRelativeTo(null);
                URL iconURL = getClass().getResource("/userInterface/Resources/logo512.png");
                ImageIcon icon = new ImageIcon(iconURL);
                about.setIconImage(icon.getImage());
                about.setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please visit our official website for repository links.");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Open an issue in the jWebProfile Github repo.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        String myString = jLabel26.getText();
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
        try {
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            URL iconURL = getClass().getResource("/userInterface/Resources/389.gif");
            ImageIcon icon = new ImageIcon(iconURL);
            //Image image = icon.getImage() ; 
            //Image newimg = image.getScaledInstance( 75, 75,  java.awt.Image.SCALE_SMOOTH ) ;  
            //icon = new ImageIcon( newimg );
            AchievementConfig config = new AchievementConfig();
            config.setIcon(icon);
            config.setDuration(3000);
            config.setBorderThickness(0);
            config.setAudioEnabled(false);
            config.setDescriptionFont(new java.awt.Font("Dialog", 0, 12));
            //config.setTitleFont(new java.awt.Font("Dialog", 0, 18));
            //config.setDistanceFromScreen(10);
            config.setAchievementPosition(AchievementPosition.BOTTOM_RIGHT);
            Achievement achievement = new Achievement("", "Bitcoin address is copied to clipboard", config);
            AchievementQueue queue = new AchievementQueue();
            queue.add(achievement);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        // TODO add your handling code here:
        jLabel26.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        jPanel7.repaint();
    }//GEN-LAST:event_jTabbedPane1MouseClicked
    ActionListener resultButtonListener1 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent eve) {
            Task2 task = new Task2();
            task.setEvent(eve);
            task.execute();

        }
    };

    ActionListener resultButtonListener2 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent eve) {
            //call the UltimateProfileViewer
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        javax.swing.JFrame jWebProfileui = new ProfileUI(con, eve.getActionCommand());
                        jWebProfileui.setLocationRelativeTo(null);
                        URL iconURL = getClass().getResource("/userInterface/Resources/logo512.png");
                        ImageIcon icon = new ImageIcon(iconURL);
                        jWebProfileui.setIconImage(icon.getImage());
                        jWebProfileui.setVisible(true);
                    } catch (Exception e) {
                        System.out.println(e);
                    }

                }
            });

        }
    };

    ActionListener resultButtonListener3 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent eve) {
            //for github
            Task4 task = new Task4();
            task.setEvent(eve);
            task.execute();

        }
    };
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
