/*
 * Year: 2017
 */
package userInterface;

import applicationLogic.DatabaseActivity;
import applicationLogic.GithubSetupLogic;
import applicationLogic.HelperClass;
import applicationLogic.TwitterSetupLogic;
import java.net.URL;
import java.sql.Connection;
import javafx.application.Platform;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.jachievement.Achievement;
import org.jachievement.AchievementConfig;
import org.jachievement.AchievementPosition;
import org.jachievement.AchievementQueue;
import twitter4j.Twitter;
import twitter4j.auth.AccessToken;
import twitter4j.auth.RequestToken;

/**
 *
 * @author nandan
 */
public class SetupAccountsUI extends javax.swing.JFrame {

    /**
     * Creates new form SetupAccountsUI
     */
    private String twitterAuthLink;
    private Twitter twitter;
    private RequestToken requestToken;
    private AccessToken accessToken;
    private TwitterSetupLogic twitterLogic;
    Browser browser = new Browser();
    Connection con;
    //String code; //for github
    //String state; //for github
    GithubSetupLogic githubSetupLogic;
    SplashScreen splash;

    public SetupAccountsUI(Connection con, SplashScreen splash) {
        this.con = con;
        githubSetupLogic = new GithubSetupLogic();
        twitterLogic = new TwitterSetupLogic();
        this.splash = splash;
        initComponents();
        jButton4.setEnabled(false);
        if (DatabaseActivity.checkTwitterSessionTable(con)) {
            jButton1.setEnabled(false);
            jTextField1.setEnabled(false);
            jButton2.setEnabled(false);
        }
        if (DatabaseActivity.checkGithubSessionTable(con)) {
            jButton3.setEnabled(false);
            //jButton4.setEnabled(true);
        } else {
            jButton4.setVisible(true);
            jButton4.setEnabled(false);
        }
        splash.setVisible(false);
        splash.dispose();
        try {
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            URL iconURL = getClass().getResource("/userInterface/Resources/496.gif");
            ImageIcon icon = new ImageIcon(iconURL);
            //Image image = icon.getImage() ; 
            //Image newimg = image.getScaledInstance( 75, 75,  java.awt.Image.SCALE_SMOOTH ) ;  
            //icon = new ImageIcon( newimg );
            AchievementConfig config = new AchievementConfig();
            config.setIcon(icon);
            config.setDuration(10000);
            config.setBorderThickness(0);
            config.setAudioEnabled(false);
            config.setDescriptionFont(new java.awt.Font("Dialog", 0, 12));
            //config.setTitleFont(new java.awt.Font("Dialog", 0, 18));
            //config.setDistanceFromScreen(10);

            config.setAchievementPosition(AchievementPosition.BOTTOM_RIGHT);
            Achievement achievement = new Achievement("Welcome!", "Need assistance on how to use this software? visit https://jwebprofile.blogspot.com", config);
            AchievementQueue queue = new AchievementQueue();
            queue.add(achievement);

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/twitter icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Click the twitter icon and enter the code below");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Okay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Resources/github icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Click the github icon to setup");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Continue");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Okay");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            jButton1.setEnabled(false);
            twitter = twitterLogic.getTwitterObj();
            requestToken = twitterLogic.pullRequestToken(twitter);

            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    Platform.setImplicitExit(false);
                    Browser browser = new Browser();
                    try {
                        browser.initAndShowGUI(twitterLogic.pullAuthorizationURL(requestToken), "twitter", con, githubSetupLogic);

                    } catch (Exception e) {
                        System.out.println(e);
                    }

                }
            });
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {

            accessToken = twitterLogic.pullAccessToken(requestToken, jTextField1.getText());
            DatabaseActivity.twitterSessionInsert(con, accessToken.getScreenName(), accessToken.getToken(), accessToken.getTokenSecret());
            JOptionPane.showMessageDialog(null, "You have successfully configured your Twitter setup!");
            jButton2.setEnabled(false);
            jTextField1.setEnabled(false);
            if (DatabaseActivity.checkSessionsTable(con)) {
                jButton4.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Oops! There was some problem with the configuration. \nPlease visit our website for assistance.");
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Platform.setImplicitExit(false);
                Browser browser = new Browser();

                try {
                    browser.initAndShowGUI(githubSetupLogic.getAuthorizationURL(), "github", con, githubSetupLogic);
                    if (DatabaseActivity.checkSessionsTable(con)) {
                        jButton4.setEnabled(true);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }

            }
        });
        jButton3.setEnabled(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        HelperClass helper = new HelperClass(con, splash);
        try {
            helper.startHomePageUI();
            dispose();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (DatabaseActivity.checkSessionsTable(con)) {
            jButton4.setEnabled(true);
            JOptionPane.showMessageDialog(null, "You have successfully configured your Github account");
            jButton5.setEnabled(false);
        } else if (DatabaseActivity.checkGithubSessionTable(con)) {
            JOptionPane.showMessageDialog(null, "You have successfully configured your Github account");
            jButton5.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Could not set the github account. Please visit our website for assistance");
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
