/*
 * Year: 2017
 */
package userInterface;

import applicationLogic.WikipediaInfo;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author nandan
 */
public class WikipediaView extends javax.swing.JFrame {

    /**
     * Creates new form WikipediaView
     */
    String refinedName;
    String user;
    private int clickCount = 0;
    private boolean done = false;
    WikipediaInfo wikiInfo = new WikipediaInfo();

    public WikipediaView(String user) {
        initComponents();
        this.user = user;
        jButton1.setVisible(true);

        try {
            jLabel1.setText(wikiInfo.getWikiSummary(user));
            WikipediaInfo.summaryText = wikiInfo.getWikiSummary(user);
        } catch (Exception e) {
            jLabel1.setText("No content found.");
            WikipediaInfo.summaryText = "no content found :(";
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Nothing to show here :(");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 940, 410));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("More Info:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setText("(This information will appear if the user is of public interest. Sometimes the information may not be received due to unexpected errors)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setText("Suggestion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            clickCount++;
            String input = user;
            String regexp = "(.+)\\s+(.+)\\s+(.+)";

            Pattern pattern = Pattern.compile(regexp);
            Matcher matcher = pattern.matcher(input);
            matcher.find();
            refinedName = matcher.group(1) + " " + matcher.group(3);
            jButton1.setText("Couldn't figure out \"" + user + "\". Maybe you should try \"" + refinedName + "\"! Click here");

            if (clickCount == 2) {
                //jButton1.setVisible(false);
                jButton1.setText("If still didn't get it, Try one last time!");
                jLabel1.setText(wikiInfo.getWikiSummary(refinedName));
                WikipediaInfo.summaryText = wikiInfo.getWikiSummary(refinedName);
            }
            if (clickCount == 3) {
                jLabel1.setText(wikiInfo.getWikiSummary(user + "."));
                jButton1.setVisible(false);
                WikipediaInfo.summaryText = wikiInfo.getWikiSummary(user + ".");
            }
        } catch (Exception e) {
            jLabel1.setText("No content found.");
            WikipediaInfo.summaryText = "no content found :(";
            jButton1.setVisible(false);
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
